version: '3.3'
services:
  redis:
    image: redis
    volumes:
      - ./Redis/data:/data
      - ./Redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  bank_central_router_manager:
      build:
        image: wagomez087/bank_central_router_manager
      depends_on:
        - redis
        - jobrunner
      ports:
        - "9299:9299"
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure

  broker_user_manager:
    build:
      context: ../BestelVoicePorts
      dockerfile: DockerfileUserManager
    depends_on:
      - redis
    ports:
      - "9099:9099"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
        replicas: 1
        restart_policy:
          condition: on-failure

  jobrunner:
    image: ansible-flask-app
    ports:
      - "9999:5000"
    deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
  
